import 'package:hive_ce_flutter/hive_flutter.dart';
import '../core/constants/app_constants.dart';
import '../models/expense.dart';
import '../models/income.dart';
import '../models/task_item.dart';
import '../models/spending_limit.dart';

/// Central service for Hive database initialization and box access.
///
/// Call [init] once in main.dart before runApp.
class HiveService {
  HiveService._();

  // ── Box References ────────────────────────────────────────────────────
  static late Box<Expense> expenseBox;
  static late Box<Income> incomeBox;
  static late Box<TaskItem> taskBox;
  static late Box<dynamic> settingsBox;

  /// Initialize Hive, register adapters, and open all boxes.
  static Future<void> init() async {
    // Initialize Hive with Flutter path
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    Hive.registerAdapter(ExpenseAdapter());
    Hive.registerAdapter(IncomeAdapter());
    Hive.registerAdapter(TaskItemAdapter());
    Hive.registerAdapter(SpendingLimitAdapter());

    // Open typed boxes
    expenseBox = await Hive.openBox<Expense>(AppConstants.expenseBox);
    incomeBox = await Hive.openBox<Income>(AppConstants.incomeBox);
    taskBox = await Hive.openBox<TaskItem>(AppConstants.taskBox);
    settingsBox = await Hive.openBox<dynamic>(AppConstants.settingsBox);
  }

  // ── Convenience Getters ───────────────────────────────────────────────

  /// Get all expenses as a list, sorted by date descending (newest first).
  static List<Expense> getAllExpenses() {
    final list = expenseBox.values.toList();
    list.sort((a, b) => b.date.compareTo(a.date));
    return list;
  }

  /// Get all incomes as a list, sorted by date descending.
  static List<Income> getAllIncomes() {
    final list = incomeBox.values.toList();
    list.sort((a, b) => b.date.compareTo(a.date));
    return list;
  }

  /// Get all tasks as a list, sorted by time ascending (earliest first).
  static List<TaskItem> getAllTasks() {
    final list = taskBox.values.toList();
    list.sort((a, b) => a.time.compareTo(b.time));
    return list;
  }

  /// Get the saved spending limit, or a default if none exists.
  static SpendingLimit getSpendingLimit() {
    final stored = settingsBox.get(AppConstants.spendingLimitKey);
    if (stored is SpendingLimit) return stored;
    return SpendingLimit();
  }

  /// Save the spending limit to settings.
  static Future<void> saveSpendingLimit(SpendingLimit limit) async {
    await settingsBox.put(AppConstants.spendingLimitKey, limit);
  }

  /// Close all open boxes (call on app dispose if needed).
  static Future<void> close() async {
    await Hive.close();
  }
}
