// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:personal_life_manager/models/expense.dart';
import 'package:personal_life_manager/models/income.dart';
import 'package:personal_life_manager/models/spending_limit.dart';
import 'package:personal_life_manager/models/task_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseAdapter());
    registerAdapter(IncomeAdapter());
    registerAdapter(SpendingLimitAdapter());
    registerAdapter(TaskItemAdapter());
  }
}
